### ISSUE TITLE
Empty value with array doesn't work as expected

### ISSUE THREAD

**Issue by sstok** [rollerworks/rollerworks-datagrid#14]
The following snip-it with all mapping field values set to null:

```
$datagrid->addColumn(
    $datagridFactory->createColumn(
        'name',
        'text',
        $datagrid,
        [
            'label' => 'Name',
            'field_mapping' => ['lastName', 'firstName', 'middleName'],
            'empty_value' => ['[None]', '[None]', ''],
            'value_glue' => ', ',
        ]
    )
);
```

Doesn't work (array type is not accepted) and after changing that it gives the following exception: 
`Empty-value of mapping field "0" doesn't exists in field mapping.`

The `ValueFormatTransformer` expects fields for 'empty_value' as an associative array `'lastName' => 'value', ...` but field_mapping is a numeric-indexed array.

**Comment by sstok** [comment]
Never mind, this works.

```
'empty_value' => [
                        'lastName' => '[None]',
                        'firstName' => '[None]',
                        'middleName' => ''
                    ],
```

**Comment by sstok** [comment]
But the accepted value-types need to be updated still!

**Comment by cordoval** [comment]
bump :older_man:

**Comment by sstok** [comment]
Done :+1:
