### ISSUE TITLE
Reokace action (multiple) in favor of one action + compound_column

### ISSUE THREAD

**Issue by sstok** [rollerworks/rollerworks-datagrid#18]
The action types has an internal options resolver making it impossible to extend the type.
So instead I'm proposing to replace the actions type with a new type "action", each "action" has a label, url / uri_schema, attr, url_attr etc.

> url can be a full url, uri_schema is for dynamic URI's (callcack or pattern)
> for SfBundle this will add route_name as alternative for URL's.

Then when you want to show multiple actions, you use the "compound_column" type to add group multiple action columns :+1:

**Comment by cordoval** [comment]
where is the branch?

**Comment by sstok** [comment]
Resolved

**Comment by cordoval** [comment]
what is Reokace ?

**Comment by sstok** [comment]
Typo :)
